imports:
    - php

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'src/Volo/*/Tests/'
        - 'src/Foodpanda/'

tools:
    php_analyzer:
        config:
            use_statement_fixes: false
            doc_comment_fixes: false
            reflection_fixes: false
    php_code_sniffer:
        enabled: true
        filter:
            paths:
                - 'src/*'
            excluded_paths:
                - 'src/Volo/*/Tests/*'
        config:
            ruleset: app/Resources/tools/phpcs.xml

    sensiolabs_security_checker: true

checks:
    php:
        verify_property_names: true
        code_rating: true
        duplication: true
        variable_existence: true
        useless_calls: true
        use_statement_alias_conflict: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        deprecated_code_usage: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        avoid_useless_overridden_methods: true
        avoid_conflicting_incrementers: true
        assignment_of_null_return: true
        uppercase_constants: true
        too_many_arguments: true
        symfony_request_injection: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        spacing_of_function_arguments: true

build:
    dependencies:
        override:
            - true
        before:
            - sudo apt-get update
            - sudo apt-get install -y graphicsmagick libgraphicsmagick1-dev
            - npm install -g grunt-cli
            - gem install sass -v '~> 3.4.13'
            - npm install
            - npm install -g bower
            - COUNTRY_CODE=test SYMFONY_ENV=test composer install --no-interaction
            - COUNTRY_CODE=test app/console fos:js-routing:dump --env=test
    project_setup:
        before:
            - grunt
    tests:
        override:
            -
                command: 'phpunit -c app/ --coverage-clover="build/logs/clover.xml"'
                environment: { COUNTRY_CODE: 'test' }
                idle_timeout: 3500
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
    environment:
        php:
            version: 5.5.14
