language: php
php:
  - 5.5

env:
   global:
     - COUNTRY_CODE=test

sudo: false

addons:
  apt:
    packages:
      - graphicsmagick
      - libgraphicsmagick1-dev

before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - gem update --system
    - gem install sass -v '~> 3.4.13'
    - sed "s/asset_version_placeholder/'${TRAVIS_COMMIT:0:7}\'/g" -i app/config/config.yml
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    # Install composer dependencies
    #    - cd $TRAVIS_BUILD_DIR && composer self-update
    - cd $TRAVIS_BUILD_DIR && composer install --no-interaction --optimize-autoloader
    - php app/console assets:install web --env=test
    - php app/console volo:thumbor:dump --env=test
    - php app/console foodora:translations:sync --env=test
    - npm install
    - grunt deploy --env=prod

cache:
    # Cache composer packages
    apt: true
    directories:
        - $HOME/.composer
        - node_modules
        - bower_components

before_script:
    # Prepare cache folders for WWW. Cache gets cleared with composer install.
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/cache
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/logs

script:
    - phpunit -c $TRAVIS_BUILD_DIR/app/
    - grunt test --env=prod

notifications:
  slack:
    rooms:
      - secure: "H5zMWPF6M5dNc4Yf31kTJkhDdQpDzJSCleSClz7kekjCTe28OwlDpe7N7nKG3QpYowHM/DU+ii8ll9z4PmsjoTKN7+tQrUiM6E4G6mHkEZwqrQAfRX99OImK/+Nsu85YcDsdImSDxRWI8SUknKaibS+aKBROr2q23Ixc+jZjlnM="
    on_success: [change]
    on_failure: [always]
    on_pull_requests: false

  email:
    on_success: [change]
    on_failure: [always]

before_deploy:
    - $TRAVIS_BUILD_DIR/build-tools/create-artifact-archive -o $TRAVIS_BUILD_DIR/build-tools/build.tar.gz -b $TRAVIS_BRANCH -c $TRAVIS_COMMIT
    - gem install mime-types -v 2.6.2

deploy:
    provider: releases
    api-key: "4f43a5306c7dfbc3e7ab9d1d6791de2e4d98a711"
    file: $TRAVIS_BUILD_DIR/build-tools/build.tar.gz
    skip_cleanup: true
    on:
        tags: true
        all_branches: true
        condition: $TRAVIS_PHP_VERSION != hhvm
