language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - hhvm
    - 7

before_install:
    - sudo apt-get update > /dev/null

install:
    # Install composer dependencies
    - cd $TRAVIS_BUILD_DIR && composer self-update
    - cd $TRAVIS_BUILD_DIR && composer install --dev --no-interaction --optimize-autoloader

cache:
    # Cache composer packages
    apt: true
    directories:
        - $HOME/.composer

before_script:
    # Prepare cache folders for WWW. Cache gets cleared with composer install.
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/cache
    - cd $TRAVIS_BUILD_DIR && chmod -R 777 app/logs

branches:
  only:
    - master
    - develop
    - /^feature\/SGFD-.*$/
    - /^hotfix\/.*$/

script:
    - phpunit -c $TRAVIS_BUILD_DIR/app/

notifications:
  slack:
    rooms:
      - hydrolo:W3sf04Zamqrz1d0CMFW3omV2#general
      - hydrolo:W3sf04Zamqrz1d0CMFW3omV2#builds
