imports:
    - { resource: config_production.yml }

parameters:
    google_tag_manager_container_id: 'GTM-MMWRXS'
    trackjs_application: 'foodora-staging'

monolog:
    handlers:
        slack:
            channel:    C0920RZ46
