imports:
    - { resource: config.yml }

framework:
    session:
        handler_id:     session.handler.redis
        cookie_lifetime: 31536000 # 60 * 60 * 24 * 365 * 1 = one year
        gc_maxlifetime: 31536000 # 60 * 60 * 24 * 365 * 1 = one year
    validation:
        cache: apc

monolog:
    channels: ["api"]
    handlers:
        api:
            type:     syslog
            level:    error
            handler:  nested
            channels: ['api']
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels:     ['!api']
        nested:
            type:     syslog
            ident:    symfony_volo_%environment%_%country_code%
            facility: local7
            level:    debug
        console:
            type:  console

doctrine_cache:
    providers:
        configuration_cache:
            type: apc
