imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1
        packages:
            cdn_s3:
                base_urls:
                    [ "%volo_frontend.image_server_base_url%/%country_code%" ]
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        # logo image [width, height]
        logo_image_dimensions: [196, 140]
        country_code: "%country_code%"
        locale: "%locale%"
        blazy_placeholder: 'data:image/gif;base64,R0lGODdhAQABAIAAAMzMzJaWliwAAAAAAQABAAACAkQBADs='

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false

doctrine_cache:
    providers:
        translator_cache:
            namespace: %country_code%_%kernel.environment%_translator_cache
            type: php_file
        configuration_cache:
            namespace: %country_code%_%kernel.environment%_configuration_cache
            type: file_system
        vendor_cache:
            namespace: %country_code%_%kernel.environment%_vendor_cache
            type: file_system

foodpanda_web_translate_it:
    base_url: %foodpanda_web_translate_it_base_url%
    public_api_key: %foodpanda_web_translate_it_public_api_key%
    private_api_key: %foodpanda_web_translate_it_private_api_key%
    main_translation_label: %foodpanda_web_translate_it_main_translation_label%

jb_phumbor:
    server:
        url: %volo_frontend.thumbor_base_url%
        secret: %volo_frontend.thumbor_secret%
    # by convention all the trasnformations starting with "bp_" define the breakpoints
    transformations:
        # start of the breakpoints definition
        bp_300:
            resize: { width: 300, height: 0 }
        bp_300_retina:
            resize: { width: 600, height: 0 }

        bp_400:
            resize: { width: 400, height: 0 }
        bp_400_retina:
            resize: { width: 800, height: 0 }

        bp_600:
            resize: { width: 600, height: 0 }
        bp_600_retina:
            resize: { width: 1200, height: 0 }

        bp_800:
            resize: { width: 800, height: 0 }
        bp_800_retina:
            resize: { width: 1600, height: 0 }

        bp_1000:
            resize: { width: 1000, height: 0 }
        bp_1000_retina:
            resize: { width: 2000, height: 0 }

        bp_1200:
            resize: { width: 1200, height: 0 }
        bp_1200_retina:
            resize: { width: 2400, height: 0 }

        bp_1400:
            resize: { width: 1400, height: 0 }
        bp_1400_retina:
            resize: { width: 2800, height: 0 }

        bp_biggest:
            resize: { width: 2000, height: 0 }
        bp_biggest_retina:
            resize: { width: 4000, height: 0 }
        # end of the breakpoints definition

        500:
            resize: { width: 500, height: 0 }
        500_retina:
            resize: { width: 1000, height: 0 }

volo_frontend:
    api:
        configuration:
            life_time: %volo_frontend_configuration_cache_life_time%
