imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        country_code: "%country_code%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false

doctrine_cache:
    providers:
        translator_cache:
            namespace: %country_code%_%kernel.environment%_translator_cache
            type: php_file
        configuration_cache:
            namespace: %country_code%_%kernel.environment%_configuration_cache
            type: file_system

foodpanda_web_translate_it:
    base_url: %foodpanda_web_translate_it_base_url%
    public_api_key: %foodpanda_web_translate_it_public_api_key%
    private_api_key: %foodpanda_web_translate_it_private_api_key%
    main_translation_label: %foodpanda_web_translate_it_main_translation_label%

volo_frontend:
    api:
        configuration:
            life_time: %volo_frontend_configuration_cache_life_time%
