imports:
    - { resource: config.yml }

parameters:
    http_schema: https
    google_api_client_id: 'gme-rocketinternetag'
    google_api_channel: 'foodora'
    google_tag_manager_container_id: 'GTM-5WN2Q7'
    trackjs_application: 'foodora-live'

framework:
    session:
        handler_id:     session.handler.redis
        cookie_lifetime: 1209600 # 60 * 60 * 24 * 14 = two weeks
        gc_maxlifetime: 1209600 # 60 * 60 * 24 * 14 = two weeks
    validation:
        cache: apc

monolog:
    handlers:
        api:
            type:     syslog
            level:    error
            handler:  nested
        wit:
            type:     syslog
            level:    error
            handler:  nested
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:     syslog
            ident:    symfony_volo_%environment%_%country_code%
            facility: local7
            level:    debug
        newrelic:
            type:     newrelic
            level:    error
        slack:
            type:       slack
            token:      xoxp-4456203445-4434037920-8956922919-5deb02
            level:      error
            channel:    C08U6G1A6
            icon_emoji: ':scream:'
            bot_name:   '%country_code%'
            include_extra: true
            use_short_attachment: true
        console:
            type:  console

doctrine_cache:
    providers:
        api_cache:
            type: redis
            redis:
              host: %redis_cache_host%
              port: %redis_cache_port%
        translator_cache:
            type: redis
            redis:
              host: %redis_cache_host%
              port: %redis_cache_port%
        schedule_cache:
            type: redis
            redis:
              host: %redis_cache_host%
              port: %redis_cache_port%
        vendor_cache:
            type: redis
            redis:
              host: %redis_cache_host%
              port: %redis_cache_port%
        special_instructions_cache:
            type: redis
            redis:
              host: %redis_cache_host%
              port: %redis_cache_port%
