imports:
    - { resource: config_development.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

parameters:
    foodpanda.api.handler: guzzle.ring.client.mock_handler
    average_delivery_time: 30
    is_coming_soon_enabled: false
    timepicker_date_format: 'eee MMM d'
    supported_locales: [%locale%]
    translator_fallback_languages: ['en']
    localeSettings:
        detectBrowserLanguage: true
        locales: %supported_locales%
        localeMapping: []
        defaultLocale: %locale%

