imports:
    - { resource: config.yml }

parameters:
    http_schema: https
    google_tag_manager_container_id: 'GTM-5WN2Q7'
    trackjs_application: 'foodora-live'
    cms_clear_cache_password: 'foodora-live-cms-clear-cache'

framework:
    validation:
        cache: apc

monolog:
    handlers:
        api:
            type:     syslog
            level:    error
            handler:  nested
        wit:
            type:     syslog
            level:    error
            handler:  nested
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:     syslog
            ident:    symfony_volo_%environment%_%country_code%
            facility: local7
            level:    debug
        newrelic:
            type:     newrelic
            level:    error
        slack:
            type:       slack
            token:      xoxp-14431811152-16294526577-17865942848-abd1035c97
            level:      error
            channel:    C0HPWB4LA
            icon_emoji: ':scream:'
            bot_name:   '%country_code%'
            include_extra: true
            use_short_attachment: true
        console:
            type:  console

doctrine_cache:
    providers:
        api_cache:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
        translator_cache:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
        schedule_cache:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
        vendor_cache:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
        special_instructions_cache:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
        cms:
            type: redis
            redis:
              connection_id: volo_frontend_redis_connection_service
