imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: revision.yml }

parameters:
    http_schema: http
    google_api_client_id: ''
    google_api_channel: ''
    google_tag_manager_container_id: ''
    monolog.handler.newrelic.class: Volo\FrontendBundle\EventListener\NewRelicHandler
    monolog.handler.slack.class: Volo\FrontendBundle\EventListener\SlackHandler
    localeSettings:
        detectBrowserLanguage: %detect_browser_language_enabled%
        locales: %supported_locales%
        localeMapping: %short_to_full_locale_name_mapping%
        defaultLocale: %locale%

framework:
    #esi:             ~
    translator:      { fallbacks: %translator_fallback_languages% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: asset_version_placeholder
        packages:
            cdn_s3:
                version: asset_version_cdn_s3_placeholder
                base_urls:
                    [ "%volo_frontend.image_server_base_url%/%country_code%" ]
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        # logo image [width, height]
        logo_image_dimensions: [195, 195]
        country_code: "%country_code%"
        locale: "%locale%"
        blazy_placeholder: 'data:image/gif;base64,R0lGODdhAQABAIAAAMzMzJaWliwAAAAAAQABAAACAkQBADs='
        google_api_client_id: "%google_api_client_id%"
        google_api_channel: '%google_api_channel%'
        timezone: '%timezone%'
        google_tag_manager_container_id: %google_tag_manager_container_id%
        average_delivery_time: '%average_delivery_time%'
        locales: "%supported_locales%"
        address_config: '%address_config%'
        assets_version: asset_version_placeholder

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false

monolog:
    channels: ["api", "wit"]
    handlers:
        api:
            type:   stream
            path:   "%kernel.logs_dir%/api-%kernel.environment%.log"
            level:  debug
            channels: ['api']
        wit:
            type:   stream
            path:   "%kernel.logs_dir%/wit-%kernel.environment%.log"
            level:  debug
            channels: ['wit']
        main:
            type:   stream
            path:   "%kernel.logs_dir%/app-%kernel.environment%.log"
            level:  debug
            channels: ['!api', '!wti']

doctrine_cache:
    providers:
        api_cache:
            namespace: %country_code%_%kernel.environment%_api_cache
            type: php_file
        translator_cache:
            namespace: %country_code%_%kernel.environment%_translator_cache
            type: php_file
        schedule_cache:
            namespace: %country_code%_%kernel.environment%_schedule_cache
            type: php_file
        configuration_cache:
            namespace: %country_code%_%kernel.environment%_configuration_cache
            type: file_system
        vendor_cache:
            namespace: %country_code%_%kernel.environment%_vendor_cache
            type: file_system
        health_check_redis:
            redis:
                connection_id: volo_frontend_redis_connection_service

jb_phumbor:
    server:
        url: %volo_frontend.thumbor_base_url%
        secret: %volo_frontend.thumbor_secret%
    # by convention all the trasnformations starting with "bp_" define the breakpoints
    transformations:
        # start of the breakpoints definition
        bp_default:
            resize: { width: 2000, height: 0 }
            filters:
                - { name: "quality", arguments: [60] }
        bp_default_retina:
            resize: { width: 4000, height: 0 }
            filters:
                - { name: "quality", arguments: [40] }
        bp_300:
            resize: { width: 300, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        bp_300_retina:
            resize: { width: 600, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

        bp_400:
            resize: { width: 400, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        bp_400_retina:
            resize: { width: 800, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

        bp_600:
            resize: { width: 600, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        bp_600_retina:
            resize: { width: 1200, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

        bp_800:
            resize: { width: 800, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        bp_800_retina:
            resize: { width: 1600, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

        bp_1000:
            resize: { width: 1000, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        bp_1000_retina:
            resize: { width: 2000, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

        bp_1200:
            resize: { width: 1200, height: 0 }
            filters:
                - { name: "quality", arguments: [60] }
        bp_1200_retina:
            resize: { width: 2400, height: 0 }
            filters:
                - { name: "quality", arguments: [40] }

        bp_1400:
            resize: { width: 1400, height: 0 }
            filters:
                - { name: "quality", arguments: [60] }
        bp_1400_retina:
            resize: { width: 2800, height: 0 }
            filters:
                - { name: "quality", arguments: [40] }

        bp_biggest:
            resize: { width: 2000, height: 0 }
            filters:
                - { name: "quality", arguments: [60] }
        bp_biggest_retina:
            resize: { width: 4000, height: 0 }
            filters:
                - { name: "quality", arguments: [40] }
        # end of the breakpoints definition

        500:
            resize: { width: 400, height: 0 }
            filters:
                - { name: "quality", arguments: [80] }
        500_retina:
            resize: { width: 800, height: 0 }
            filters:
                - { name: "quality", arguments: [45] }

volo_frontend:
    api:
        configuration:
            life_time: %volo_frontend_configuration_cache_life_time%

foodpanda_api_health:
    enabled: ['version', 'session', 'cache']
    prefix: 'health_check.'
#    sqs_endpoint: %aws_sqs_elasticsearch_update_queue%

jms_i18n_routing:
    default_locale: %locale%
    locales: %supported_locales%
    strategy: prefix_except_default

fos_js_routing:
    cache_control:
        public: true
        expires: 1 days
        vary: [ Cookie, Accept, Accept-Language ]
