imports:
    - { resource: config_production.yml }

parameters:
    google_tag_manager_container_id: 'GTM-MMWRXS'
    trackjs_application: 'foodora-staging'
    cms_clear_cache_password: 'foodora-staging-cms-clear-cache'

twig:
    strict_variables: true

monolog:
    handlers:
        slack:
            channel:    C0920RZ46
