redirect_terms:
    path: /terms
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: cms
        code: terms-and-conditions.htm
        permanent: true

redirect_drivers:
    path: /drivers
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: cms
        code: drivers-and-restaurants.htm
        permanent: true

redirect_restaurants:
    path: /restaurants
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: cms
        code: drivers-and-restaurants.htm
        permanent: true

redirect_imprint:
    path: /imprint
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: cms
        code: imprint.htm
        permanent: true

redirect_privacy:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: cms
        code: privacy.htm
        permanent: true

redirect_city_munchen:
    path: /city/munchen
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: volo_location_search_vendors_by_city
        cityUrlKey: muenchen
        permanent: true

redirect_city_koeln:
    path: /city/koln
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: volo_location_search_vendors_by_city
        cityUrlKey: koeln
        permanent: true

redirect_city_duesseldorf:
    path: /city/dusseldorf
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: volo_location_search_vendors_by_city
        cityUrlKey: duesseldorf
        permanent: true

redirect_city:
    path: /r/{cityUrlKey}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: volo_location_search_vendors_by_city
        permanent: true

redirect_location:
    path: /location/{urlKey}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: vendor_by_url_key
        permanent: true

redirect_signup:
    path: /signup
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: login
        permanent: true
