volo_redirects:
    resource: "routing-redirects.yml"

volo_frontend:
    resource: "@VoloFrontendBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%http_schema%]

logout:
    path:     /logout
    schemes:  [%http_schema%]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

foodpanda_web_health:
    resource: "@FoodpandaApiHealthBundle/Controller/CheckController.php"
    type:     annotation
    prefix:   /health
