security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            simple_form:
                authenticator: volo_frontend.api_authenticator
                login_path: /login
                check_path: /login_check

            logout:
                path:   /logout
                target: / 
