security:
    session_fixation_strategy: migrate

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            simple_form:
                authenticator: volo_frontend.security.authenticator
                login_path: /login
                check_path: /login_check
                use_referer: true
                success_handler: volo_frontend.security.ajax_authentication_success_handler
                require_previous_session: false

            logout:
                path:   /logout
                target: / 
