imports:
    - { resource: common.yml }
parameters:
    locale: en_AE
    timezone: "Asia/Dubai"
    average_delivery_time: 30
    is_coming_soon_enabled: true
    address_config:
        postal_code_field:
            - 'postal_code'
            - 'neighborhood'
            - 'administrative_area_level_1'
        autocomplete_type:
            - "address"
        hide_checkout_postal_code: true
