imports:
    - { resource: common.yml }
parameters:
    locale: en
    timezone: "Asia/Dubai"
    average_delivery_time: 30
    is_coming_soon_enabled: false

    short_to_full_locale_name_mapping:
        en: 'en_AE'

    address_config:
        postal_code_field:
            - 'postal_code'
            - 'sublocality'
            - 'sublocality_level_1'
            - 'neighborhood'
            - 'administrative_area_level_1'
        street_field:
            - 'route'
            - 'intersection'
            - 'premise'
            - 'neighborhood'
        autocomplete_type: []
        hide_checkout_postal_code: false
