parameters:
    is_coming_soon_enabled: false
    timepicker_date_format: 'eee MMM d'
    detect_browser_language_enabled: true
    translator_fallback_languages: ['en']
    short_to_full_locale_name_mapping: []
    supported_locales: [%locale%]
    address_config:
        map_enabled: false
        postal_code_field:
            - 'postal_code'
        street_field:
            - 'route'
        autocomplete_type:
            - "(regions)"
        hide_checkout_postal_code: false

    sitemap.s3.base_url: https://foodora-sitemap.s3.eu-central-1.amazonaws.com/production/%country_code%
