imports:
    - { resource: common.yml }
parameters:
    locale: de_DE
    timezone: "Europe/Berlin"
    average_delivery_time: 30
    address_config:
        postal_code_field:
            - 'postal_code'
            - 'neighborhood'
            - 'administrative_area_level_1'
        autocomplete_type:
            - "address"
        hide_checkout_postal_code: false
        required_fields:
            - "latitude"
            - "longitude"
            - "city"
            - "postcode"
            - "street"
            - "building"
