imports:
    - { resource: common.yml }
parameters:
    locale: es_ES
    timezone: "Europe/Madrid"
    average_delivery_time: 30
    address_config:
        autocomplete_type:
            - "address"
