imports:
    - { resource: common.yml }
parameters:
    locale: fi_FI
    timezone: "Europe/Helsinki"
    average_delivery_time: 30
    timepicker_date_format: 'eee d LLL'
    address_config:
        autocomplete_type:
            - "address"
        format: ':street :building, :plz :city'
        valid_address_input: '.*'
        hide_checkout_postal_code: false
