imports:
    - { resource: common.yml }
parameters:
    locale: fr_FR
    timezone: "Europe/Paris"
    average_delivery_time: 30
    address_config:
        autocomplete_type:
            - "address"
        format: ':building :street, :plz'
