imports:
    - { resource: common.yml }
parameters:
    locale: en_HK
    timezone: "Asia/Hong_Kong"
    average_delivery_time: 30

    supported_locales: [%locale%, zh]
    address_config:
        postal_code_field:
            - 'postal_code'
            - 'neighborhood'
            - 'administrative_area_level_1'
        autocomplete_type:
            - "address"
        hide_checkout_postal_code: true

    short_to_full_locale_name_mapping:
        zh: zh_HK
        en: en_HK
