imports:
    - { resource: common.yml }
parameters:
    locale: nb_NO
    timezone: "Europe/Oslo"
    average_delivery_time: 30
    address_config:
        map_enabled: true
        update_map_input: true
        postal_code_field:
            - 'postal_code'
        autocomplete_type:
            - "address"
        hide_checkout_postal_code: false
        required_fields:
            - "street"
            - "building"
            - "postcode"
            - "city"
        format: ':street :building, :plz :city'
        valid_address_input: "\\D+"
