imports:
    - { resource: common.yml }
parameters:
    locale: sv_SE
    timezone: "Europe/Stockholm"
    average_delivery_time: 30
    address_config:
        autocomplete_type:
            - "address"
        format: ':street :building, :plz :city'
        valid_address_input: '.*'
        hide_checkout_postal_code: false
        map_enabled: true
        update_map_input: true
        required_fields:
            - "street"
            - "building"
            - "postcode"
            - "city"
