imports:
    - { resource: dist/common.yml }

parameters:
    country_code: de
    country_domain: localhost
    environment: test
    locale: de

    # 'guzzle.ring.client.curl_handler' or 'guzzle.ring.client.mock_handler'
    foodpanda.api.handler: guzzle.ring.client.mock_handler
    foodpanda.api.base_url: http://localhost/api/v4
